# Generated by Django 3.0.3 on 2020-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200821_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
